name: Node CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
    - name:  Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
    - name: npm install, build
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
        
    - name: Deploy to Github Package Registry
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=$(node tasks/next-dev-version.js)
        npm --no-git-tag-version version ${VERSION}
        npm publish --tag dev
        
    - name: Build & Push Docker image
      env:
        DOCKER_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker build . --file Dockerfile --tag docker.pkg.github.com/iMilad/mg-football-fe/mgf:1.0.0
        docker login docker.pkg.github.com -u iMilad -p ${DOCKER_AUTH_TOKEN}
        docker push docker.pkg.github.com/iMilad/mg-football-fe/mgf:1.0.0
      
